
all:
	@g++ -c approx_equal.c
	@g++ -c main.c
	@g++ -c check_SolveSquare.c
	@g++ -c SolveSquare.c
	@g++ -c compare.c
	@g++ -c line_equation.c
	@g++ -c Modes.c

	@g++ main.o approx_equal.o SolveSquare.o check_SolveSquare.o compare.o line_equation.o Modes.o -o proga.exe

